#!/bin/sh

staged_files=$(git diff --diff-filter=d --staged --name-only | grep -E 'src\/\S*\.ts$')
if [ -n "$staged_files" ]
	then
	if ! npm run lint:fix
		then
		exit 1
	fi

	git add "$staged_js_files"
fi
